substitutions:
  _JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
steps:
  # Gradlew 실행 허용
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        chmod +x ./gradlew
  # JDK 11 설치 및 환경 설정
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y openjdk-11-jdk
        export JAVA_HOME=$_JAVA_HOME
        export PATH=$JAVA_HOME/bin:$PATH
  # 스프링 부트 애플리케이션 빌드
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: /bin/bash
    args:
      - '-c'
      - './gradlew clean bootJar -x test'
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/truetree-cloud-run:$SHORT_SHA'
      - '.'
  # Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/truetree-cloud-run:$SHORT_SHA']

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'truetree-cloud-run', '--image', 'gcr.io/$PROJECT_ID/truetree-cloud-run:$SHORT_SHA', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/truetree-cloud-run:$SHORT_SHA'

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
