
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.22.110.202:3306/fcdb
    username: root
    password: howtofactcheck

logging:
  level:
    org.hibernate.SQL: debug

